### ISSUE TITLE
Search Results

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#112]
https://bloomington.in.gov/search/node?keys=website

Search results are showing up with incorrect dates for the documents.
I am not able to find the recent website press release.
Search navigation links are showing up un-styled at well.

**Comment by charlesbrandt** [comment]
I believe that the issue with press releases should be resolved; we may not have imported old press releases at the time this issue was reported. 

However, I don't think we need to show the date or author in search results. These are for when the page was created. Often there have been many updates and other contributors, so this information is not helpful in search results. 

Search pagination results still need styling.

**Comment by inghamn** [comment]
The information displayed in the search results, for each node, is controlled by the view modes.  There's no code changes to do for altering that.

I'll work on some CSS for pagination.  Any requests on what we want pagination to look like?

**Comment by rbdietz** [comment]
Google material design is a good start.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov

**Comment by laurahaley** [comment]
I'd like the search results numbers to carry through sequentially if possible and not start at 1 for each page

**Comment by charlesbrandt** [comment]
Thanks for the suggestion, Laura. It sounds like Drupal search results don't include any position details, so we'll have trouble knowing what the correct numbers are. Drupal even handles the pagination, so we can't calculate based on current page. We're thinking about dropping the numbers in this next update.

**Comment by rbdietz** [comment]
How are we on drupal updates.  current?  behind?





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov
