### ISSUE TITLE
View block is missing after a page is edited

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-theme-cob#127]
On the [engineering projects page](https://bloomington.in.gov/engineering/projects), the main list of projects is now generated by a drupal View block. Whenever a change is made to the page's content, that view block disappears. It is possible to bring it back manually by clearing the cache in Drupal. 

Is there a way to re-render the view block after a change to the content is made?

**Comment by inghamn** [comment]
I've posted a question about this on the Drupal forms.
https://www.drupal.org/forum/support/post-installation/2018-03-12/view-block-doesnt-render-after-editing-node
We'll see if anybody has some ideas.  Otherwise, I'll probably delete the view altogether and write custom code into the theme to pull the project nodes.
