### ISSUE TITLE
Call to action links need formatting

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-theme-cob#15]
Currently "Call to Action" links are not being formatted with the solid green button called for in the design. An example page that has a Call to Action link is available here:

https://bloomington.in.gov/alpha/latino

Current:
<img width="322" alt="screen shot 2017-05-09 at 2 00 03 pm" src="https://cloud.githubusercontent.com/assets/2225624/25865199/2218a3a8-34c0-11e7-8f7c-0add000486cc.png">
Goal:
<img width="393" alt="screen shot 2017-05-09 at 1 59 47 pm" src="https://cloud.githubusercontent.com/assets/2225624/25865205/2b3dcbf2-34c0-11e7-9dff-77cd95280362.png">

**Comment by schnippy** [comment]
For this, I've updated to add in the styles for a specific cta-button class to make it closer to the design. 

For the "Call to Action" field label, we should disable this through the manage display options
	
/admin/structure/types/manage/book/display

![screen shot 2017-05-21 at 9 58 34 pm](https://cloud.githubusercontent.com/assets/439451/26312264/0a570484-3ed5-11e7-81df-4b45b025581f.png)

We should also disable the same for the Facebook field since this is covered in the node.html.twig 

```
node.html.twig:            {% if contactInfo.links.facebook %}
node.html.twig:                <dd><a href="{{ contactInfo.links.facebook }}" class="facebook">Connect on Facebook</a></dd>

So it is appearing twice:


![screen shot 2017-05-21 at 9 37 19 pm](https://cloud.githubusercontent.com/assets/439451/26312272/13bd3908-3ed5-11e7-8de5-59d134d8ec36.png)

```

**Comment by inghamn** [comment]
I'm moving this change into the Factory Number 1 CSS.  There are many other buttons on the site that are supposed to look the same as the user-supplied CTA links.
