### ISSUE TITLE
OOTM Issues 

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/drupal-theme-cob#97]
Add Press Releases as a Related Category to /mayor and /ootm

Add a page for Speeches as a related category to /mayor and /ootm

Create speeches page is needed.  We might want to create a "Speech" content type to allow for aggregation on this page.  OOTM will populate speeches.

**Comment by quarterback** [comment]
I created a page for mayor's speeches and remarks. Speeches can be added manually, as they proliferate, a separate content type for speeches. 
https://bloomington.in.gov/mayor/speeches

Releases will be trickier, because there's no "news department" to point to, but I point to "news releases" (/news) page in those instances. 

Working with mayor's office now to show them how to add remarks to main page.

**Comment by quarterback** [comment]
Speeches & Remarks are a separate category, that autogenerate their own URLs. Right now are manually linked to a speeches page.
